services:
  internal-site-init:
    image: magic-compare/internal-site:ci
    build:
      context: .
      dockerfile: docker/internal-site.Dockerfile

  internal-site:
    image: magic-compare/internal-site:ci
    build:
      context: .
      dockerfile: docker/internal-site.Dockerfile
    volumes:
      - internal-data:/app/data

  rustfs:
    volumes:
      - rustfs-data:/data

volumes:
  rustfs-data:
  internal-data:
