services:
  internal-site-init:
    image: magic-compare/internal-site:local
    build:
      context: .
      dockerfile: docker/internal-site.Dockerfile

  internal-site:
    image: magic-compare/internal-site:local
    build:
      context: .
      dockerfile: docker/internal-site.Dockerfile
