x-local-internal-site: &local-internal-site
  image: magic-compare/internal-site:local
  build:
    context: .
    dockerfile: docker/internal-site.Dockerfile

services:
  internal-site-init:
    <<: *local-internal-site

  internal-site:
    <<: *local-internal-site
